default_stages: [commit, push]

repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args:
          - "--line-length=120"
          - "--target-version=py38"
          - "--target-version=py39"
          - "--target-version=py310"
          - "--target-version=py311"
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        exclude: src/adapters/alembic
        args:
          - "--line-length=120"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: no-commit-to-branch

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell

  - repo: https://github.com/snakemake/snakefmt
    rev: v0.8.4
    hooks:
      - id: snakefmt
        args:
          - "--line-length=120"
